### PR TITLE
Conform dataset ref to Nat SciData format

### PR DESCRIPTION
**Pull request by NickRaymondKurtansky**

### CODE REVIEW

**Comment by brianhelba** [comment]
@NickRaymondKurtansky Should this be merged?

**Comment by NickRaymondKurtansky** [comment]
Hi Brian,

No because Dan already merged one of these pull requests I put in at
https://challenge2020.isic-archive.com/ . It was for the Nature Scientific
Data reference update. I was hoping to make the change at
https://challenge.isic-archive.com/data next.

--

*N*icholas *K*urtansky

**Review by NickRaymondKurtansky — COMMENTED** [review]
Sorry Brian. I was wrong. This merge stills needs to be made.

**Comment by brianhelba** [comment]
@NickRaymondKurtansky You should now have permission to merge this yourself. Feel free to do so whenever you're satisfied with the content.

**Pull request closed without merging**
